// Project management: CRUD + ZIP export.
// A Project groups multiple "model sets" (each generated from one JSON paste).
// In the exported ZIP, model sets land under lib/features/<feature>/models/...
// preserving the api_*/pm_* folder convention.
//
// Project shape:
//   {
//     id:           string,
//     name:         string,
//     description:  string,
//     createdAt:    iso,
//     updatedAt:    iso,
//     modelSets: [
//       {
//         id:        string,
//         featureName: string,           // e.g. "audit"
//         mode:      "api" | "param",
//         rootKey:   string,
//         options:   { ... },            // captured at save time, used to re-generate if edited
//         json:      string,             // the original pasted JSON (for docs)
//         files:     [{ path, content, className }],
//         createdAt: iso,
//       }
//     ]
//   }

import { loadState, saveState } from "./storage.js";
import { convertServiceDart } from "./convertService.js";

function uid() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
}

export function listProjects() {
  const state = loadState();
  return Object.values(state.projects).sort(
    (a, b) => new Date(b.updatedAt) - new Date(a.updatedAt),
  );
}

export function getProject(id) {
  return loadState().projects[id] || null;
}

export function createProject({ name, description }) {
  const state = loadState();
  const id = uid();
  const now = new Date().toISOString();
  state.projects[id] = {
    id,
    name: name.trim(),
    description: (description || "").trim(),
    createdAt: now,
    updatedAt: now,
    modelSets: [],
  };
  saveState(state);
  return state.projects[id];
}

export function deleteProject(id) {
  const state = loadState();
  delete state.projects[id];
  saveState(state);
}

export function addModelSet(projectId, modelSet) {
  const state = loadState();
  const p = state.projects[projectId];
  if (!p) throw new Error("Project not found");
  const id = uid();
  const now = new Date().toISOString();
  p.modelSets.push({ id, createdAt: now, ...modelSet });
  p.updatedAt = now;
  saveState(state);
  return id;
}

export function deleteModelSet(projectId, modelSetId) {
  const state = loadState();
  const p = state.projects[projectId];
  if (!p) return;
  p.modelSets = p.modelSets.filter((ms) => ms.id !== modelSetId);
  p.updatedAt = new Date().toISOString();
  saveState(state);
}

// Build a ZIP for an entire project.
// Layout:
//   <projectName>/
//     lib/
//       features/
//         <feature>/
//           models/
//             api_xxx/...
//             pm_xxx/...
//       core/
//         utils/
//           convert_service.dart   (only if any model set uses ConvertService)
//     README.md
export async function buildProjectZip(project) {
  const zip = new JSZip();
  const root = zip.folder(slugify(project.name));

  let usesConvertService = false;
  const lib = root.folder("lib");
  const features = lib.folder("features");

  for (const set of project.modelSets) {
    const feature = features.folder(slugify(set.featureName));
    const modelsFolder = feature.folder("models");
    for (const file of set.files) {
      modelsFolder.file(file.path, file.content);
    }
    if (set.options?.useConvertService) usesConvertService = true;
  }

  if (usesConvertService) {
    lib.folder("core").folder("utils").file("convert_service.dart", convertServiceDart());
  }

  root.file("README.md", projectReadme(project));
  return zip.generateAsync({ type: "blob" });
}

function projectReadme(p) {
  const lines = [
    `# ${p.name}`,
    "",
    p.description || "_No description._",
    "",
    `Generated by **JSON → Dart Advanced**.`,
    "",
    `## Model sets`,
    "",
  ];
  for (const set of p.modelSets) {
    lines.push(`### ${set.featureName} · \`${set.rootKey}\` (${set.mode})`);
    lines.push("");
    lines.push("| Class | File |");
    lines.push("|---|---|");
    for (const f of set.files) {
      lines.push(`| \`${f.className}\` | \`${f.path}\` |`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

export function slugify(s) {
  return String(s || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "")
    .replace(/_+/g, "_");
}
